# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50, verbose_name='收货人名称')),
                ('u_iphone', models.CharField(max_length=12, verbose_name='收货人手机')),
                ('u_fixphone', models.CharField(max_length=10, verbose_name='固定电话')),
                ('u_address', models.CharField(max_length=255, verbose_name='收货地址')),
                ('u_detail', models.CharField(max_length=100, verbose_name='地址详细')),
                ('u_postcode', models.CharField(max_length=7, verbose_name='邮编')),
                ('u_status', models.IntegerField(default=0, verbose_name='默认地址')),
                ('u_addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('u_altertime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'mall_user_address',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=50, verbose_name='品牌名称')),
                ('b_logo', models.ImageField(default='/static/default/timg.jpg', upload_to='images/brand/', verbose_name='品牌logo')),
                ('b_intro', models.TextField(max_length=255, verbose_name='品牌简介')),
                ('b_isdel', models.CharField(default='启用', max_length=4, verbose_name='品牌简介')),
                ('b_addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('b_altertime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'mall_brand',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('g_title', models.CharField(max_length=255, verbose_name='简短介绍')),
                ('g_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('g_saleprice', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='商品折扣')),
                ('g_address', models.CharField(default='', max_length=255, verbose_name='商品产地')),
                ('g_type', models.IntegerField(default=0, verbose_name='商品所属类别')),
                ('g_mall', models.CharField(default='', max_length=4, verbose_name='是否包邮')),
                ('g_nums', models.IntegerField(default=0, verbose_name='商品数量')),
                ('g_invnum', models.IntegerField(default=0, verbose_name='商品库存')),
                ('g_sellnum', models.IntegerField(default=0, verbose_name='商品售卖数量')),
                ('g_isdel', models.IntegerField(default=1, verbose_name='商品状态')),
                ('g_intro', models.CharField(max_length=255, verbose_name='商品简介')),
                ('g_addtime', models.DateTimeField(auto_now_add=True, verbose_name='商品添加时间')),
                ('g_altertime', models.DateTimeField(auto_now=True, verbose_name='商品修改时间')),
            ],
            options={
                'db_table': 'mall_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=30, verbose_name='商品特征名称')),
                ('a_pid', models.IntegerField(default=0, verbose_name='父级id')),
                ('a_info', models.CharField(default='暂无简介', max_length=50, verbose_name='特征简介')),
                ('a_isdel', models.IntegerField(default=1, verbose_name='特征状态')),
                ('a_path', models.CharField(default='', max_length=30, verbose_name='所属父类路径')),
                ('a_addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('a_altertime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'mall_goodsattr',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_info', models.TextField(default='暂无商品详情', verbose_name='商品详情')),
                ('i_color', models.CharField(default='', max_length=30, verbose_name='商品颜色')),
                ('i_size', models.CharField(default='', max_length=30, verbose_name='商品尺寸')),
                ('i_pinpai', models.CharField(default='', max_length=30, verbose_name='商品品牌')),
                ('i_hot', models.IntegerField(default=0, verbose_name='')),
                ('i_gid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='back.Goods')),
            ],
            options={
                'db_table': 'mall_goodsinfo',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_pic', models.CharField(max_length=100, verbose_name='商品图片')),
                ('d_num', models.IntegerField(default=0, verbose_name='购买的商品数量')),
                ('d_gid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='back.Goods', verbose_name='商品id')),
            ],
            options={
                'db_table': 'mall_order_detail',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_number', models.CharField(max_length=20, verbose_name='订单编号')),
                ('o_totalprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单总价')),
                ('o_totalnum', models.IntegerField(default=0, verbose_name='订单商品总数量')),
                ('o_status', models.IntegerField(default=1, verbose_name='订单状态')),
                ('o_addtime', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('o_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='back.Address', verbose_name='订单收货地址')),
            ],
            options={
                'db_table': 'mall_orders',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255, verbose_name='图片名称')),
                ('p_pic', models.ImageField(default='/static/default/timg.jpg', max_length=255, upload_to='images/goods/', verbose_name='商品图片')),
                ('p_sort', models.IntegerField(default=0, verbose_name='图片排序标示')),
                ('p_cover', models.IntegerField(default=0, verbose_name='封面图面标示')),
                ('p_isdel', models.IntegerField(default=1, verbose_name='图片是否前台显示')),
                ('p_addtime', models.DateTimeField(auto_now_add=True, verbose_name='图片添加时间')),
                ('p_altertime', models.DateTimeField(auto_now=True, verbose_name='图片修改时间')),
                ('p_gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Goods', verbose_name='图片所属商品id')),
            ],
            options={
                'db_table': 'mall_pictures',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30, verbose_name='类别名称')),
                ('t_pid', models.IntegerField(default=0, verbose_name='父级栏目id')),
                ('t_path', models.CharField(default='', max_length=30, verbose_name='类别路径')),
                ('t_info', models.CharField(max_length=50, verbose_name='栏目简介')),
                ('t_icon', models.CharField(default='fa-black-tie', max_length=50, verbose_name='栏目图标')),
                ('t_isdel', models.IntegerField(default=1, verbose_name='是否删除')),
                ('t_addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('t_altertime', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'db_table': 'mall_types',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=80, verbose_name='登录密码')),
                ('truename', models.CharField(default='', max_length=20, verbose_name='真实姓名')),
                ('sex', models.CharField(default='男', max_length=1, verbose_name='性别')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('u_address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('u_phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('u_email', models.CharField(default='', max_length=30, verbose_name='邮箱')),
                ('u_pic', models.FileField(default='/static/default/timg.jpg', upload_to='images/user/', verbose_name='用户头像')),
                ('u_status', models.CharField(default='未审核', max_length=10, verbose_name='用户状态')),
                ('u_intro', models.TextField(default='这家伙很懒', verbose_name='用户介绍')),
                ('u_addtime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'db_table': 'mall_user',
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'mall_user_level',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='u_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='back.UserLevel', verbose_name='用户等级'),
        ),
        migrations.AddField(
            model_name='orders',
            name='o_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.User', verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='d_oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Orders', verbose_name='订单id'),
        ),
        migrations.AddField(
            model_name='goods',
            name='g_tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Types', verbose_name='商品类别'),
        ),
        migrations.AddField(
            model_name='brand',
            name='b_tid',
            field=models.ManyToManyField(to='back.Types'),
        ),
        migrations.AddField(
            model_name='address',
            name='u_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.User', verbose_name='会员id'),
        ),
    ]
