# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20180703_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='o_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Address', verbose_name='订单收货地址'),
        ),
    ]
