# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20180703_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='d_gid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.Goods', verbose_name='商品id'),
        ),
    ]
