# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_auto_20180703_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'permissions': (('show_goodspic', '商品图片查看权限'), ('edit_goodspic', '商品图片修改权限'), ('insert_goodspic', '商品图片增加权限'), ('del_goodspic', '商品图片删除权限'))},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'permissions': (('show_brand', '品牌查看权限'), ('edit_brand', '品牌修改权限'), ('insert_brand', '品牌增加权限'), ('del_brand', '品牌删除权限'))},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'permissions': (('show_goods', '商品模块查看权限'), ('edit_goods', '商品模块修改权限'), ('insert_goods', '商品模块增加权限'), ('del_goods', '商品模块删除权限'))},
        ),
        migrations.AlterModelOptions(
            name='goodsattr',
            options={'permissions': (('show_attr', '商品属性模块查看权限'), ('edit_attr', '商品属性模块修改权限'), ('insert_attr', '商品属性模块增加权限'), ('del_attr', '商品属性模块删除权限'))},
        ),
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'permissions': (('show_goodsinfo', '商品信息查看权限'), ('edit_goodsinfo', '商品信息修改权限'), ('insert_goodsinfo', '商品信息增加权限'), ('del_goodsinfo', '商品信息删除权限'))},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'permissions': (('show_order', '订单查看权限'), ('edit_order', '订单修改权限'), ('insert_order', '订单增加权限'), ('del_order', '订单删除权限'))},
        ),
        migrations.AlterModelOptions(
            name='pictures',
            options={'permissions': (('show_goodspic', '商品图片查看权限'), ('edit_goodspic', '商品图片修改权限'), ('insert_goodspic', '商品图片增加权限'), ('del_goodspic', '商品图片删除权限'))},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'permissions': (('show_types', '商品类别模块查看权限'), ('edit_types', '商品类别模块修改权限'), ('insert_types', '商品类别模块增加权限'), ('del_types', '商品类别模块删除权限'))},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('show_user', '会员模块查看权限'), ('edit_user', '会员模块修改权限'), ('insert_user', '会员模块增加权限'), ('del_user', '会员模块删除权限'))},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
