# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_auto_20180704_0859'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='mall_user',
        ),
    ]
