# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_auto_20180704_0925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.AlterModelTable(
            name='users',
            table='mall_users',
        ),
    ]
