# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('back', '0007_auto_20180704_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_icon', models.CharField(default='/static/default/timg.jpg', max_length=100)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_info',
            },
        ),
    ]
